#! /bin/sh
t=$(date +%s)
ts=$(date +'%Y-%m-%dT%H:%M:%S')

last=""
out=""
for i in $@
do
  if [ "$last" = "-o" ]
  then
    out="$i"
  fi

  last=$i
done

if [ "$out" = "" ]
then
  out=$(echo $@|tr ' /' '\n\n'|tail -1)
fi

rc=0
env CCACHE_DIR=${HOME}/dev/.ccache CCACHE_NODIRECT=1 ccache /opt/rh/devtoolset-4/root/usr/bin/g++.original "$@"
rc=$?


printf '\033[1;32m%s | %s | %03d | %s\033[0m\n' "$ts" "$(date +'%Y-%m-%dT%H:%M:%S')" $(($(date +%s) - $t)) $out | tee -a /tmp/g++.times 1>&2

exit $rc
