#! /bin/sh

last=""
out=""
for i in $@
do
  if [ "$last" = "-o" ]
  then
    out="$i"
  fi

  last=$i
done

if [ "$out" = "" ]
then
  out=$(echo $@|tr ' /' '\n\n'|tail -1)
fi

rc=0
tmpf=$(mktemp --tmpdir g++.times.XXXXXXXXXX)
env -u SUNPRO_DEPENDENCIES env CCACHE_DIR=${HOME}/dev/.ccache CCACHE_NODIRECT=1 /usr/bin/time --output=$tmpf --format "$out | %E | %s | %U | %M" ccache /opt/rh/devtoolset-4/root/usr/bin/g++.original "$@"
rc=$?

(
  flock -e 200
  cat $tmpf >> /tmp/g++.times.new
  printf '\033[1;32m%s\033[0m\n' "$(cat $tmpf)" 1>&2
  rm -f $tmpf
) 200>/tmp/g++.times.lock

exit $rc
